steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/gfsa-fe:$SHORT_SHA', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/gfsa-fe:$SHORT_SHA']
  - name: 'gcr.io/cloud-builders/kubectl'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [[ "$BRANCH_NAME" == "dev" ]]; then
          NAMESPACE="dev"
        elif [[ "$BRANCH_NAME" == "qa" ]]; then
          NAMESPACE="qa"
        elif [[ "$BRANCH_NAME" == "uat" ]]; then
          NAMESPACE="uat"
        else
          echo "Unknown branch: $BRANCH_NAME"
          exit 1
        fi
        export NAMESPACE
        export SHORT_SHA=$SHORT_SHA  # Ensure SHORT_SHA is available
        envsubst < deployment.yaml | kubectl apply -f - -n $NAMESPACE
        envsubst < service.yaml | kubectl apply -f - -n $NAMESPACE
        envsubst < ingress.yaml | kubectl apply -f - -n $NAMESPACE
images:
  - 'gcr.io/$PROJECT_ID/gfsa-fe:$SHORT_SHA'
options:
  logging: CLOUD_LOGGING_ONLY