steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/gfsa-fe:$SHORT_SHA', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/gfsa-fe:$SHORT_SHA']
  - name: 'gcr.io/cloud-builders/kubectl'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [[ "$BRANCH_NAME" == "dev" ]]; then
          NAMESPACE="dev"
        elif [[ "$BRANCH_NAME" == "qa" ]]; then
          NAMESPACE="qa"
        elif [[ "$BRANCH_NAME" == "uat" ]]; then
          NAMESPACE="uat"
        else
          echo "Unknown branch: $BRANCH_NAME"
          exit 1
        fi
        sed -i "s/{{NAMESPACE}}/$NAMESPACE/g" deployment.yaml
        sed -i "s/{{IMAGE_TAG}}/$SHORT_SHA/g" deployment.yaml
        sed -i "s/{{NAMESPACE}}/$NAMESPACE/g" service.yaml
        kubectl apply -f deployment.yaml
        kubectl apply -f service.yaml
images:
  - 'gcr.io/$PROJECT_ID/gfsa-fe:$SHORT_SHA'
options:
  logging: CLOUD_LOGGING_ONLY