import { Noto_Sans } from "next/font/google";
import Link from "next/link";
import styles from "./rootStyle.module.css";
import "./globals.css";

const fontFamily = Noto_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={fontFamily.className}>
      <body>
        <header>
          <nav>
            <ul>
              <li>
                <Link className={styles.homeLink} href={"/home"}>
                  Globomantics Home
                </Link>
              </li>
              <li>
                <Link className={styles.menuBarLink} href={"/blog"}>
                  Blog
                </Link>
              </li>
              <li>
                <Link className={styles.menuBarLink} href={"/settings"}>
                  Settings
                </Link>
              </li>
              <li>
                <Link className={styles.menuBarLink} href={"/conference"}>
                  Conference
                </Link>
              </li>
            </ul>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
